### ISSUE TITLE
Fringe Coordinates Overload Map

### ISSUE THREAD

**Issue by yhhjo** [yhhjo/OverpassR#14]
Clicking or manually entering coordinates on the poles renders a large output table with no overpass dates or PR information. (e.g. type 90, 90 into lon/lat search function). I suspect this is due to all of the paths passing over the pole? 

@SimonTopp @johngardner87 Can we limit user input to a smaller range that does not overload the map with high tile density locations, or should users be able to search for overpasses in the poles?

**Comment by SimonTopp** [comment]
We can just limit the valid search range to exclude the polls.  If we're having rendering issues for other high latitude spots with lots of overlapping tiles then we might want to look into the leaflet_gl that Matt suggested!
