### ISSUE TITLE
Precision of Acquisition Swaths

### ISSUE THREAD

**Issue by yhhjo** [yhhjo/OverpassR#15]
Acquisition swaths are generated by the ESA as an acquisition tool. They imprecisely connect the edges of MGRS tiles photographed in the same ~15 minute timespan. The geometry is simplified.

When someone clicks on the map, I look at which MGRS tile(s) contain the click and which acquisition swaths intersect the click. I use the date on the swath to calculate when the MGRS tile will be photographed in the user's chosen date range. It's my de-facto "lookup table." 

Because swaths are imprecise, they sometimes do not contain the entire tile: st_contains does not work. Here is one example of the click, MGRS tile, and all swaths: 

<img width="417" alt="Screen Shot 2020-06-09 at 1 31 15 PM" src="https://user-images.githubusercontent.com/59706404/84198220-1090f200-aa58-11ea-9756-d6a669f4e894.png">

Individual swaths--none overlap entirely:

<img width="402" alt="Screen Shot 2020-06-09 at 1 37 06 PM" src="https://user-images.githubusercontent.com/59706404/84198292-2dc5c080-aa58-11ea-8eb5-818c74766570.png">
<img width="222" alt="Screen Shot 2020-06-09 at 1 37 33 PM" src="https://user-images.githubusercontent.com/59706404/84198298-2f8f8400-aa58-11ea-9884-9e7f3fe61d41.png">
<img width="187" alt="Screen Shot 2020-06-09 at 1 37 51 PM" src="https://user-images.githubusercontent.com/59706404/84198301-31f1de00-aa58-11ea-8662-02331e47f31b.png">

How much overlap suggests a tile is part of an acquisition swath? Is there a function that calculates if one polygon contains at least n% of another polygon?

**Comment by yhhjo** [comment]
Update: I said if the MGRS tile overlaps a swath by at least 90% then it is considered to be part of that swath. Thoughts? @SimonTopp @johngardner87

**Comment by SimonTopp** [comment]
I think it'd be a little better to go with the approach we talked about in the meeting.  Sentinel 2 isn't always acquired for the entire tile, so the best approach is probably if the actual point clicked overlaps with the swath then it's considered part of the it rather than the 90% metric.  Does that make sense? @yhhjo

**Comment by yhhjo** [comment]
@SimonTopp Got it, thanks. That's way faster to compute as well.
