### ISSUE TITLE
Merging Attributes Across Spatial Data Frames

### ISSUE THREAD

**Issue by yhhjo** [yhhjo/OverpassR#18]
https://github.com/yhhjo/OverpassR/blob/9c6e2f80e6cf30882b0d9ad1d066400565d1c14d/Swaths.R#L25-L38

I have the 27,000+ MGRS tiles set to undergo an individual st_intersect in one massive for loop that takes ages to run. Is there a faster way of seeing which swath a tile _most_ overlaps with, then copying the overpass and time info for that swath into the tile's dataframe? It needs to handle the case of multiple overlaps, such as in high latitudes.

_Context_:
Swaths.R is a working draft of a backend program that can pull the latest ESA Acquisition Swaths kml, read it, and update the local shape file 'MGRS'  with overpass and time attributes. This data changes slightly month to month. Currently, overpass data is pulled from the Sentinel Acquisition kml files that are read directly by the main program, and _no._ time of day is included. I want to eliminate the swaths file by storing overpass and time of day data directly in the mgrs spatial data frame.

**Comment by yhhjo** [comment]
@SimonTopp

**Comment by SimonTopp** [comment]
Hey Andrew.  If I understand the issue correctly, then I'd suggest this alternative.  Rather than intersecting the swaths with the tiles, just intersect the point clicked on the map with the swaths and pull the time from that.  Really we're not interested in what swath overlaps 'the most' with what tile, what we want to know is the time at the exact point clicked by the user.  Does that make sense?  That way you're also not running st_intersect over 27,000+ tiles (if you do want to do this though, I think you can accomplish what you want by setting st_join = st_nearest within your st_intersect call.)

**Comment by yhhjo** [comment]
@SimonTopp Thanks for checking in! 

Not sure I was as precise in my issue above. 

In the context of a backend script, we don't have a user's click. This script I'm working on is intended to streamline the front-end calculations by writing over the MGRS local file with all relevant data so we don't even need to handle swaths. The idea is to have one data frame, MGRS, that has the tiles **names** and **geometry** while attributes **time** and **overpass**  update as ESA publishes new acquisition swaths. 

I suspect that having one data frame of 27,000 polygons with 4 attributes each will yield faster performance than loading two separate spatial data frames: one with the geometry and one with the overpass data. 

I'm curious to hear your thoughts on this!

**Comment by yhhjo** [comment]
@johngardner87 @SimonTopp Thank you for the ideas today. These are the two lines of code we should pick apart:

https://github.com/yhhjo/OverpassR/blob/9c6e2f80e6cf30882b0d9ad1d066400565d1c14d/OverpassR.R#L338
https://github.com/yhhjo/OverpassR/blob/9c6e2f80e6cf30882b0d9ad1d066400565d1c14d/OverpassR.R#L46

Instead of manipulating a Date object, we will pass a POSIXct (date and time combo) into these two functions. There are likely Lubridate functions that can handle math with Datetime objects only manipulate the day units. Here's an algorithm that would work:

1. Read the Datetime (POSIXct object) from each swath that intersects the user's click. It's stored under swaths$begin.
2. Find the whole number of days between the swath's reference datetime and the start of the user's selected date range.
3. Modulo that whole number by 5 [sentinel return period], and add the result to the start of the date range to get the first overpass within the user's selected range. 
4. Add the Time attribute to this **first overpass within range** 
4. Increment **first overpass** by 5 days while preserving the time until a datetime is outside of the date range. 
5. Save all of these 5-day increments as Datetime objects. 
6. Merge this array of Datetime objects with the array of all MGRS tiles that also the click (creates _all possible_ tile-datetime combos since Sentinel acquires images by swath, not by tile).
7. Generate the output table.

**Comment by SimonTopp** [comment]
@yhhjo Just wanted to let you know I haven't 'totally' dropped the ball on this.  I opened the code yesterday and started playing with it a little.  I think it'll be pretty straightforward to incorporate the time aspect using lubridate.  I'm feeling a bit overextended right now but I'll hope back in when I get a second.

**Comment by yhhjo** [comment]
@SimonTopp No worries - I just had 2 exams and evacuated the wildfires in CA so I haven't had a chance to do much either this week. On it now.

**Comment by yhhjo** [comment]
@SimonTopp @johngardner87 

Can Sentinel put Datetime data the "Dates" column of the output table while Landsat only puts a Date, or will this be too confusing for the eye? Alternative is the "Time of Day" column only for Sentinel, but this monkeys with the algorithm I just implemented.
