### ISSUE TITLE
Revise output table

### ISSUE THREAD

**Issue by johngardner87** [yhhjo/OverpassR#7]
One way the output table could be formatted for easy digesting then downloading and manipulating is shown in this google sheet (with examples of simple version as is, with lat long, and with shapefile).

https://docs.google.com/spreadsheets/d/17LVDM54wS_6PioGgOuTHivjUSNpWFGAll6FK7Phxpms/edit?usp=sharing

**Comment by yhhjo** [comment]
@johngardner87 Got it. Thanks!
