### ISSUE TITLE
Validate User Input

### ISSUE THREAD

**Issue by yhhjo** [yhhjo/OverpassR#8]
https://github.com/yhhjo/OverpassR/blob/a7ecd4395979c9a6f7695a4191ecab0795cff915/OverpassR.R#L139-L141

The "validate" function in line 139 prevents the tiles from being rendered if invalid date range is selected (good), but it does not display the error message. 

I need to figure out how to an error message, not just avoid crashing the app. Any thoughts on workarounds @johngardner87 @SimonTopp ?

**Comment by SimonTopp** [comment]
According to https://shiny.rstudio.com/articles/validation.html.  The validate() call needs to come after a render or reactive call.  I moved it into the code where you render the global table and it seems to work alright.  I think this will work with your "Please enter valid coordinates" error as well, maybe throw that in where you render the leaflet?

Code added at line 221
`#Display table
    output$table <<- renderDT(
      validate(
        need((as.numeric(input$dates[2] - input$dates[1]) >=16), message =  "Please enter valid date range")
      ),
      global_table, options = list(paging = FALSE, searching = FALSE, info = FALSE) 
    )`
